name: terraform-plan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      CF_DNS_TOKEN: ${{ secrets.CF_DNS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Export TF Vars
        run: |
          export TF_VAR_cf_account_id="${CF_ACCOUNT_ID}"
          export TF_VAR_cf_zone_id="${CF_ZONE_ID}"
          export TF_VAR_cf_dns_token="${CF_DNS_TOKEN}"

          terraform init
          terraform validate
          terraform plan
