name: Cosign Signing
on: [workflow_dispatch]
permissions:
  contents: read
jobs:
  cosign:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: cosign version
