name: Terraform Apply
on:
  workflow_dispatch:
permissions: {contents: read}
jobs:
  apply:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: CONFIRM_APPLY=yes make tf-apply
